_welcome:
    path:     /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

index:
    path:     /login
    defaults: { _controller: AcmeDemoBundle:Login:index }


addstudent:
    path:     /addstudent
    defaults: { _controller: AcmeDemoBundle:AddStudent:addstudent }


########################################################################
#stuff
######
acme_staff_add:
    path:     /staff/add
    defaults: { _controller: AcmeDemoBundle:Staff:add }

acme_staff_show:
    pattern:  /staff/{id}
    defaults: { _controller: AcmeDemoBundle:Staff:show }

acme_staff_home:
    pattern:  /staff/
    defaults: { _controller: AcmeDemoBundle:Staff:index }

acme_staff_edit:
    pattern:  /staff/{id}/edit
    defaults: { _controller: AcmeDemoBundle:Staff:edit }
    requirements:
        id:  \d+

acme_staff_delete:
    pattern:  /staff/{id}/delete/
    defaults: { _controller: AcmeDemoBundle:Staff:delete }
    requirements:
        id:  \d+

########################################################################
#book
######
acme_book_add:
    path:     /book/add
    defaults: { _controller: AcmeDemoBundle:Book:add }

acme_book_show:
    pattern:  /book/{id}
    defaults: { _controller: AcmeDemoBundle:Book:show }

acme_book_home:
    pattern:  /book/
    defaults: { _controller: AcmeDemoBundle:Book:index }

acme_book_edit:
    pattern:  /book/{id}/edit
    defaults: { _controller: AcmeDemoBundle:Book:edit }
    requirements:
        id:  \d+

acme_book_delete:
    pattern:  /book/{id}/delete/
    defaults: { _controller: AcmeDemoBundle:Book:delete }
    requirements:
        id:  \d+

########################################################################
#link
######
acme_link_add:
    path:     /link/add
    defaults: { _controller: AcmeDemoBundle:Link:add }

acme_link_show:
    pattern:  /link/{id}
    defaults: { _controller: AcmeDemoBundle:Link:show }

acme_link_home:
    pattern:  /link/
    defaults: { _controller: AcmeDemoBundle:Link:index }

acme_link_edit:
    pattern:  /link/{id}/edit
    defaults: { _controller: AcmeDemoBundle:Link:edit }
    requirements:
        id:  \d+

acme_link_delete:
    pattern:  /link/{id}/delete/
    defaults: { _controller: AcmeDemoBundle:Link:delete }
    requirements:
        id:  \d+

########################################################################
#activity
#########
acme_activity_add:
    path:     /activity/add
    defaults: { _controller: AcmeDemoBundle:Activity:add }

acme_activity_show:
    pattern:  /activity/{id}
    defaults: { _controller: AcmeDemoBundle:Activity:show }

acme_activity_home:
    pattern:  /activity/
    defaults: { _controller: AcmeDemoBundle:Activity:index }

acme_activity_edit:
    pattern:  /activity/{id}/edit
    defaults: { _controller: AcmeDemoBundle:Activity:edit }
    requirements:
        id:  \d+

acme_activity_delete:
    pattern:  /activity/{id}/delete/
    defaults: { _controller: AcmeDemoBundle:Activity:delete }
    requirements:
        id:  \d+

########################################################################
#student
#########
acme_student_add:
    path:     /student/add
    defaults: { _controller: AcmeDemoBundle:Student:add }

acme_student_show:
    pattern:  /student/{id}
    defaults: { _controller: AcmeDemoBundle:Student:show }

acme_student_home:
    pattern:  /student/
    defaults: { _controller: AcmeDemoBundle:Student:index }

acme_student_edit:
    pattern:  /student/{id}/edit
    defaults: { _controller: AcmeDemoBundle:Student:edit }
    requirements:
        id:  \d+

acme_student_delete:
    pattern:  /student/{id}/delete/
    defaults: { _controller: AcmeDemoBundle:Student:delete }
    requirements:
        id:  \d+

########################################################################
#class
#########
acme_class_add:
    path:     /class/add
    defaults: { _controller: AcmeDemoBundle:Studentclass:add }

acme_class_show:
    pattern:  /class/{id}
    defaults: { _controller: AcmeDemoBundle:Studentclass:show }

acme_class_home:
    pattern:  /class/
    defaults: { _controller: AcmeDemoBundle:Studentclass:index }

acme_class_edit:
    pattern:  /class/{id}/edit
    defaults: { _controller: AcmeDemoBundle:Studentclass:edit }
    requirements:
        id:  \d+

acme_class_delete:
    pattern:  /class/{id}/delete/
    defaults: { _controller: AcmeDemoBundle:Studentclass:delete }
    requirements:
        id:  \d+

########################################################################
#gallery
#########
acme_gallery_add:
    path:     /gallery/add
    defaults: { _controller: AcmeDemoBundle:Gallery:add }

acme_gallery_show:
    pattern:  /gallery/{id}
    defaults: { _controller: AcmeDemoBundle:Gallery:show }

acme_gallery_home:
    pattern:  /gallery/
    defaults: { _controller: AcmeDemoBundle:Gallery:index }

acme_gallery_edit:
    pattern:  /gallery/{id}/edit
    defaults: { _controller: AcmeDemoBundle:Gallery:edit }
    requirements:
        id:  \d+

acme_gallery_delete:
    pattern:  /gallery/{id}/delete/
    defaults: { _controller: AcmeDemoBundle:Gallery:delete }
    requirements:
        id:  \d+
########################################################################
#job
#########
acme_job_add:
    path:     /job/add
    defaults: { _controller: AcmeDemoBundle:Job:add }

acme_job_show:
    pattern:  /job/{id}
    defaults: { _controller: AcmeDemoBundle:Job:show }

acme_job_home:
    pattern:  /job/
    defaults: { _controller: AcmeDemoBundle:Job:index }

acme_job_edit:
    pattern:  /job/{id}/edit
    defaults: { _controller: AcmeDemoBundle:Job:edit }
    requirements:
        id:  \d+

acme_job_delete:
    pattern:  /job/{id}/delete/
    defaults: { _controller: AcmeDemoBundle:Job:delete }
    requirements:
        id:  \d+
